# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "https://media.ffa.tw/favicon.jpg"

[footer]
since = 2016
customText = "å…¨ç«™å…§å®¹çš†å—è‘—ä½œæ¬Šæ³•ä¿è­·ï¼Œæœªç¶“åŒæ„è«‹å‹¿è½‰è¼‰ï¼Œå¦‚æ–‡å…§è¨»æ˜å¯è½‰è¼‰äº¦è«‹å‹™å¿…é™„ä¸ŠåŸæ–‡å‡ºè™•ï¼Œè¬è¬ã€‚\næœ¬ç¶²ç«™ç”± Github Pages æä¾›æœå‹™ã€åœ–åºŠç”± Microsoft Azure æä¾›æœå‹™"

[dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04+08:00"

[sidebar]
emoji = "ğŸ’»"
subtitle = "é€™è£¡æ˜¯æˆ‘çš„å€‹äººç¶²ç«™å…¼éƒ¨è½æ ¼ï¼Œæˆ‘æœƒåœ¨é€™è£¡åˆ†äº«å¿ƒæƒ…ã€ç”Ÿæ´»ã€é›»å­ç”¢å“æˆ–å…¶ä»–å¿ƒå¾—ï¼Œæ­¡è¿å¸¸ä¾†ä½œå®¢ï¼"

[sidebar.avatar]
enabled = true
local = false
src = "https://media.ffa.tw/avatar.png"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Copyright Â© Feather Akira. All rights reserved."

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = false
provider = "disqus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
